In [2]:
import pandas as pd

In [ ]:
# 시리즈 = pandas.Series(데이터)
# 데이터프레임 = pandas.DataFrame(데이터)

In [3]:
dict_data = {
    "c0": [1, 2, 3], 
    "c1": [4, 5, 6], 
    "c2": [7, 8, 9],
    "c3": [10, 11, 12], 
    "c4": [13, 14, 15]
}

df = pd.DataFrame(dict_data)
print(type(df))
print(df)

<class 'pandas.DataFrame'>
   c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15

In [4]:
# 행 인덱스 / 열 이름 설정
import pandas as pd

data = [
    [15, "남", "덕영중"],
    [17, "여", "수리중"]
]

df = pd.DataFrame(data, index=["준서", "예은"], columns=["나이", "성별", "학교"])
print(df)

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [5]:
df

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [6]:
df.index

Index(['준서', '예은'], dtype='str')

In [7]:
df.columns

Index(['나이', '성별', '학교'], dtype='str')

In [8]:
df

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [10]:
df.index = ["학생1", "학생2"]
df

     나이 성별   학교
학생1  15  남  덕영중
학생2  17  여  수리중

In [12]:
df.columns = ["연령", "남녀", "소속"]
df

     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [13]:
import pandas as pd

data = [
    [15, "남", "덕영중"],
    [17, "여", "수리중"]
]

df = pd.DataFrame(data, index=["준서", "예은"], columns=["나이", "성별", "학교"])
df

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [16]:
df = df.rename(columns={"나이":"연령", "성별":"남녀", "학교":"소속"})

In [18]:
df

    연령 남녀   소속
준서  15  남  덕영중
예은  17  여  수리중

In [20]:
df = df.rename(index={
    "준서": "학생1",
    "예은": "학생2"
})
df

     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [21]:
# 행/열 삭제
# 행삭제: DataFrame객체.drop(행인덱스 또는 배열, axis=0 또는 axis="index")
# 열삭제: DataFrame객체.drop(열이름 또는 배열, axis=1 또는 axis="columns")

import pandas as pd

exam_data  = {
    "수학": [90, 80, 70], 
    "영어": [98, 89, 95], 
    "음악": [85, 95, 100], 
    "체육": [100, 90, 90]
}

df = pd.DataFrame(exam_data, index=["서준", "우현", "인아"])
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [26]:
df2 = df.copy()
df2 = df2.drop("우현")
df2

    수학  영어   음악   체육
서준  90  98   85  100
인아  70  95  100   90

In [27]:
df3 = df.copy()
df3 = df3.drop(["우현", "인아"], axis=0)
df3

    수학  영어  음악   체육
서준  90  98  85  100

In [28]:
df4 = df.copy()
df4 = df4.drop(["우현", "인아"], axis="index")
df4

    수학  영어  음악   체육
서준  90  98  85  100

In [29]:
df5 = df.copy()
df5 = df5.drop(index=["우현"])
df5

    수학  영어   음악   체육
서준  90  98   85  100
인아  70  95  100   90

In [32]:
# 열 삭제 
df2 = df.copy()
df2 = df2.drop("수학", axis=1)
df2

    영어   음악   체육
서준  98   85  100
우현  89   95   90
인아  95  100   90

In [33]:
df3 = df.copy()
df3 = df3.drop(["영어", "음악"], axis=1)
df3

    수학   체육
서준  90  100
우현  80   90
인아  70   90

In [34]:
df4 = df.copy()
df4 = df4.drop(["영어", "음악"], axis="columns")
df4

    수학   체육
서준  90  100
우현  80   90
인아  70   90

In [35]:
df5 = df.copy()
df5 = df5.drop(columns=["수학"])
df5

    영어   음악   체육
서준  98   85  100
우현  89   95   90
인아  95  100   90

In [36]:
# 행선택
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [37]:
df.loc["서준"]

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64

In [38]:
type(df.loc["서준"])

pandas.Series

In [40]:
label1 = df.loc["서준"]
position1 = df.iloc[0]

print(label1)
print()
print(position1)

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64

In [41]:
print(df.loc[["서준", "우현"]])
print()
print(df.iloc[[0, 1]])

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

In [42]:
type(df.loc[["서준", "우현"]])

pandas.DataFrame

In [43]:
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [44]:
# 행선택
print(df.loc["서준" : "우현"])
print()
print(df.iloc[0 : 1])

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

    수학  영어  음악   체육
서준  90  98  85  100

In [45]:
# 열선택
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [46]:
df["수학"]

서준    90
우현    80
인아    70
Name: 수학, dtype: int64

In [47]:
type(df["수학"])

pandas.Series

In [48]:
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [ ]:
df.영어
# df["영 어"]

서준    98
우현    89
인아    95
Name: 영어, dtype: int64

In [50]:
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [51]:
df[["영어", "체육"]]

    영어   체육
서준  98  100
우현  89   90
인아  95   90

In [ ]:
print(df["영어"])
print()
print(df[["영어"]])

서준    98
우현    89
인아    95
Name: 영어, dtype: int64

    영어
서준  98
우현  89
인아  95

In [ ]:
print(type(df["영어"]))
print()
print(type(df[["영어"]]))

<class 'pandas.Series'>

<class 'pandas.DataFrame'>

In [54]:
# 원소 선택
exam_data  = {
    "이름": ["서준", "우현", "인아"],
    "수학": [90, 80, 70], 
    "영어": [98, 89, 95], 
    "음악": [85, 95, 100], 
    "체육": [100, 90, 90]
}

df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [57]:
print(df.loc[0:2])
print()
print(df.iloc[0:2])

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

   이름  수학  영어  음악   체육
0  서준  90  98  85  100
1  우현  80  89  95   90

In [59]:
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [60]:
df = df.set_index("이름")
df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [63]:
df.loc["서준"]
df.iloc[0]

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64

In [64]:
df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [68]:
# df.loc["서준"]["음악"]
print(df.loc["서준", "음악"])
print()
print(df.iloc[0, 2])

85

85

In [72]:
df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [73]:
print(df.loc["서준", ["음악", "체육"]])
print()
print(df.iloc[0, [2, 3]])

음악     85
체육    100
Name: 서준, dtype: int64

음악     85
체육    100
Name: 서준, dtype: int64

In [74]:
df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [76]:
print(df.loc["서준", "음악":"체육"])
print()
print(df.iloc[0, 2:])

음악     85
체육    100
Name: 서준, dtype: int64

음악     85
체육    100
Name: 서준, dtype: int64