In [2]:
import pandas as pd

df = pd.read_csv("./data/stock-data.csv")

In [3]:
df.head()

         Date  Close  Start   High    Low  Volume
0  2018-07-02  10100  10850  10900  10000  137977
1  2018-06-29  10700  10550  10900   9990  170253
2  2018-06-28  10400  10900  10950  10150  155769
3  2018-06-27  10900  10800  11050  10500  133548
4  2018-06-26  10800  10900  11000  10700   63039

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    20 non-null     str
 1   Close   20 non-null     int64
 2   Start   20 non-null     int64
 3   High    20 non-null     int64
 4   Low     20 non-null     int64
 5   Volume  20 non-null     int64
dtypes: int64(5), str(1)
memory usage: 1.1 KB

In [5]:
df.isnull().sum()

Date      0
Close     0
Start     0
High      0
Low       0
Volume    0
dtype: int64

In [8]:
# 문자열을 Timestamp로 변환


df["new_date"] = pd.to_datetime(df["Date"])
df.head()

         Date  Close  Start   High    Low  Volume   new_date
0  2018-07-02  10100  10850  10900  10000  137977 2018-07-02
1  2018-06-29  10700  10550  10900   9990  170253 2018-06-29
2  2018-06-28  10400  10900  10950  10150  155769 2018-06-28
3  2018-06-27  10900  10800  11050  10500  133548 2018-06-27
4  2018-06-26  10800  10900  11000  10700   63039 2018-06-26

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      20 non-null     str
 1   Close     20 non-null     int64
 2   Start     20 non-null     int64
 3   High      20 non-null     int64
 4   Low       20 non-null     int64
 5   Volume    20 non-null     int64
 6   new_date  20 non-null     datetime64[us]
dtypes: datetime64[us](1), int64(5), str(1)
memory usage: 1.2 KB

In [10]:
df = df.set_index("new_date")
df = df.drop("Date", axis=1)

df.head()

            Close  Start   High    Low  Volume
new_date
2018-07-02  10100  10850  10900  10000  137977
2018-06-29  10700  10550  10900   9990  170253
2018-06-28  10400  10900  10950  10150  155769
2018-06-27  10900  10800  11050  10500  133548
2018-06-26  10800  10900  11000  10700   63039

In [11]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 20 entries, 2018-07-02 to 2018-06-01
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Close   20 non-null     int64
 1   Start   20 non-null     int64
 2   High    20 non-null     int64
 3   Low     20 non-null     int64
 4   Volume  20 non-null     int64
dtypes: int64(5)
memory usage: 960.0 bytes

In [12]:
pd.DatetimeIndex([
    "2022-12-15", "2023/01/25"
])

DatetimeIndex(['2022-12-15', '2023-01-25'], dtype='datetime64[us]', freq=None)

In [ ]:
pd.DatetimeIndex([
    "1040"
])

DateParseError: Unknown datetime string format, unable to parse: 2022_12_15

In [15]:
pd.Timestamp("2023-12-25")

Timestamp('2023-12-25 00:00:00')

In [16]:
pd.Timestamp("2023/12/25")

Timestamp('2023-12-25 00:00:00')

In [17]:
pd.Timestamp("2023:12:25")

DateParseError: hour must be in 0..23: 2023:12:25

In [18]:
pd.to_datetime("2025/12/25")

Timestamp('2025-12-25 00:00:00')

In [20]:
pd.to_datetime("2025년 12월 25일", format="%Y년 %m월 %d일")

Timestamp('2025-12-25 00:00:00')

In [21]:
pd.to_datetime("2025:12:25", format="%Y:%m:%d")

Timestamp('2025-12-25 00:00:00')

In [26]:
pd.to_datetime("05-12-23 23:59:59", format="%d-%m-%y %H:%M:%S")

Timestamp('2023-12-05 23:59:59')