In [2]:
import pandas as pd

df = pd.read_csv("./data/stock-data.csv")

In [3]:
df.head()

         Date  Close  Start   High    Low  Volume
0  2018-07-02  10100  10850  10900  10000  137977
1  2018-06-29  10700  10550  10900   9990  170253
2  2018-06-28  10400  10900  10950  10150  155769
3  2018-06-27  10900  10800  11050  10500  133548
4  2018-06-26  10800  10900  11000  10700   63039

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    20 non-null     str
 1   Close   20 non-null     int64
 2   Start   20 non-null     int64
 3   High    20 non-null     int64
 4   Low     20 non-null     int64
 5   Volume  20 non-null     int64
dtypes: int64(5), str(1)
memory usage: 1.1 KB

In [5]:
df.isnull().sum()

Date      0
Close     0
Start     0
High      0
Low       0
Volume    0
dtype: int64

In [8]:
# 문자열을 Timestamp로 변환


df["new_date"] = pd.to_datetime(df["Date"])
df.head()

         Date  Close  Start   High    Low  Volume   new_date
0  2018-07-02  10100  10850  10900  10000  137977 2018-07-02
1  2018-06-29  10700  10550  10900   9990  170253 2018-06-29
2  2018-06-28  10400  10900  10950  10150  155769 2018-06-28
3  2018-06-27  10900  10800  11050  10500  133548 2018-06-27
4  2018-06-26  10800  10900  11000  10700   63039 2018-06-26

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      20 non-null     str
 1   Close     20 non-null     int64
 2   Start     20 non-null     int64
 3   High      20 non-null     int64
 4   Low       20 non-null     int64
 5   Volume    20 non-null     int64
 6   new_date  20 non-null     datetime64[us]
dtypes: datetime64[us](1), int64(5), str(1)
memory usage: 1.2 KB

In [10]:
df = df.set_index("new_date")
df = df.drop("Date", axis=1)

df.head()

            Close  Start   High    Low  Volume
new_date
2018-07-02  10100  10850  10900  10000  137977
2018-06-29  10700  10550  10900   9990  170253
2018-06-28  10400  10900  10950  10150  155769
2018-06-27  10900  10800  11050  10500  133548
2018-06-26  10800  10900  11000  10700   63039

In [11]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 20 entries, 2018-07-02 to 2018-06-01
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Close   20 non-null     int64
 1   Start   20 non-null     int64
 2   High    20 non-null     int64
 3   Low     20 non-null     int64
 4   Volume  20 non-null     int64
dtypes: int64(5)
memory usage: 960.0 bytes

In [12]:
pd.DatetimeIndex([
    "2022-12-15", "2023/01/25"
])

DatetimeIndex(['2022-12-15', '2023-01-25'], dtype='datetime64[us]', freq=None)

In [ ]:
pd.DatetimeIndex([
    "1040"
])

DateParseError: Unknown datetime string format, unable to parse: 2022_12_15

In [15]:
pd.Timestamp("2023-12-25")

Timestamp('2023-12-25 00:00:00')

In [16]:
pd.Timestamp("2023/12/25")

Timestamp('2023-12-25 00:00:00')

In [17]:
pd.Timestamp("2023:12:25")

DateParseError: hour must be in 0..23: 2023:12:25

In [18]:
pd.to_datetime("2025/12/25")

Timestamp('2025-12-25 00:00:00')

In [20]:
pd.to_datetime("2025년 12월 25일", format="%Y년 %m월 %d일")

Timestamp('2025-12-25 00:00:00')

In [21]:
pd.to_datetime("2025:12:25", format="%Y:%m:%d")

Timestamp('2025-12-25 00:00:00')

In [26]:
pd.to_datetime("05-12-23 23:59:59", format="%d-%m-%y %H:%M:%S")

Timestamp('2023-12-05 23:59:59')

In [27]:
# timestamp를 이용해서 period로 변환

dates = ["2019-01-01", "2020-03-01", "2021-06-01"]

ts_dates = pd.to_datetime(dates)
ts_dates

DatetimeIndex(['2019-01-01', '2020-03-01', '2021-06-01'], dtype='datetime64[us]', freq=None)

In [28]:
pr_day = ts_dates.to_period(freq="D")
pr_day

PeriodIndex(['2019-01-01', '2020-03-01', '2021-06-01'], dtype='period[D]')

In [30]:
pr_month = ts_dates.to_period(freq="M")
pr_month

PeriodIndex(['2019-01', '2020-03', '2021-06'], dtype='period[M]')

In [31]:
pr_year = ts_dates.to_period(freq="Y")
pr_year

PeriodIndex(['2019', '2020', '2021'], dtype='period[Y-DEC]')

In [32]:
# 시계열 데이터 만들기 
ts_ms = pd.date_range(
    start="2024-01-01", 
    end=None, 
    periods=6, 
    freq="MS",
    tz="Asia/Seoul"
)
ts_ms

DatetimeIndex(['2024-01-01 00:00:00+09:00', '2024-02-01 00:00:00+09:00',
               '2024-03-01 00:00:00+09:00', '2024-04-01 00:00:00+09:00',
               '2024-05-01 00:00:00+09:00', '2024-06-01 00:00:00+09:00'],
              dtype='datetime64[us, Asia/Seoul]', freq='MS')

In [33]:
ts_me = pd.date_range(
    start="2024-01-01", 
    periods=6, 
    freq="ME",
    tz="Asia/Seoul"
)
ts_me

DatetimeIndex(['2024-01-31 00:00:00+09:00', '2024-02-29 00:00:00+09:00',
               '2024-03-31 00:00:00+09:00', '2024-04-30 00:00:00+09:00',
               '2024-05-31 00:00:00+09:00', '2024-06-30 00:00:00+09:00'],
              dtype='datetime64[us, Asia/Seoul]', freq='ME')

In [34]:
ts_3m = pd.date_range(
    "2024-01-01", 
    periods=6, 
    freq="3MS",
    tz="Asia/Seoul"
)

ts_3m

DatetimeIndex(['2024-01-01 00:00:00+09:00', '2024-04-01 00:00:00+09:00',
               '2024-07-01 00:00:00+09:00', '2024-10-01 00:00:00+09:00',
               '2025-01-01 00:00:00+09:00', '2025-04-01 00:00:00+09:00'],
              dtype='datetime64[us, Asia/Seoul]', freq='3MS')

In [35]:
# 시계열 데이터 활용
df = pd.read_csv("./data/stock-data.csv")
df.head()

         Date  Close  Start   High    Low  Volume
0  2018-07-02  10100  10850  10900  10000  137977
1  2018-06-29  10700  10550  10900   9990  170253
2  2018-06-28  10400  10900  10950  10150  155769
3  2018-06-27  10900  10800  11050  10500  133548
4  2018-06-26  10800  10900  11000  10700   63039

In [36]:
df["new_Date"] = pd.to_datetime(df["Date"])
df.head()

         Date  Close  Start   High    Low  Volume   new_Date
0  2018-07-02  10100  10850  10900  10000  137977 2018-07-02
1  2018-06-29  10700  10550  10900   9990  170253 2018-06-29
2  2018-06-28  10400  10900  10950  10150  155769 2018-06-28
3  2018-06-27  10900  10800  11050  10500  133548 2018-06-27
4  2018-06-26  10800  10900  11000  10700   63039 2018-06-26

In [38]:
df["new_Date"].str[0:4]

AttributeError: Can only use .str accessor with string values, not datetime64

In [41]:
df["year"] = df["new_Date"].dt.year

In [43]:
df["month"] = df["new_Date"].dt.month

In [45]:
df["day"] = df["new_Date"].dt.day

In [46]:
df.head()

         Date  Close  Start   High    Low  Volume   new_Date  year  month  day
0  2018-07-02  10100  10850  10900  10000  137977 2018-07-02  2018      7    2
1  2018-06-29  10700  10550  10900   9990  170253 2018-06-29  2018      6   29
2  2018-06-28  10400  10900  10950  10150  155769 2018-06-28  2018      6   28
3  2018-06-27  10900  10800  11050  10500  133548 2018-06-27  2018      6   27
4  2018-06-26  10800  10900  11000  10700   63039 2018-06-26  2018      6   26

In [48]:
df["Date_yr"] = df["new_Date"].dt.to_period(freq="Y")

In [49]:
df["Date_m"] = df["new_Date"].dt.to_period(freq="M")

In [50]:
df.head()

,Date,Close,Start,High,Low,Volume,new_Date,year,month,day,Date_yr,Date_m
0,2018-07-02,10100,10850,10900,10000,137977,2018-07-02,2018,7,2,2018,2018-07
1,2018-06-29,10700,10550,10900,9990,170253,2018-06-29,2018,6,29,2018,2018-06
2,2018-06-28,10400,10900,10950,10150,155769,2018-06-28,2018,6,28,2018,2018-06
3,2018-06-27,10900,10800,11050,10500,133548,2018-06-27,2018,6,27,2018,2018-06
4,2018-06-26,10800,10900,11000,10700,63039,2018-06-26,2018,6,26,2018,2018-06

In [51]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      20 non-null     str
 1   Close     20 non-null     int64
 2   Start     20 non-null     int64
 3   High      20 non-null     int64
 4   Low       20 non-null     int64
 5   Volume    20 non-null     int64
 6   new_Date  20 non-null     datetime64[us]
 7   year      20 non-null     int32
 8   month     20 non-null     int32
 9   day       20 non-null     int32
 10  Date_yr   20 non-null     period[Y-DEC]
 11  Date_m    20 non-null     period[M]
dtypes: datetime64[us](1), int32(3), int64(5), period[M](1), period[Y-DEC](1), str(1)
memory usage: 1.8 KB